name: ChatPrivate
version: '${project.version}'
main: dev.tranducminh.chatprivate.ChatPrivate
api-version: '1.20'
folia-supported: true

commands:
  whisper:
    usage: /whisper
    aliases: [w, pm, msg]
  reply:
    usage: /reply
    aliases: [r]
